[package]
name          = "river"

# VERSION NOTE:
#
# We need to start our numbering at 0.2.0, as there was a parked
# crate published using 0.1.0. We should yank that version and
# remove this comment block when publishing v0.2.0.
version       = "0.2.0"

authors       = [
    "James Munns <james@onevariable.com>",
]
edition       = "2021"
readme        = "../../README.md"
repository    = "https://github.com/memorysafety/river"
description   = "A reverse proxy application, based on the pingora library from Cloudflare"
license       = "Apache-2.0"
categories    = [

]
keywords      = [
    "proxy",
]
documentation = "https://docs.rs/river/"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]

[dependencies]
async-trait = "0.1.79"
log = "0.4.21"
tokio = "1.37.0" # TODO: check for implicit feature usage
toml = "0.8.12"
tracing = "0.1.40"

[dependencies.tracing-subscriber]
version  = "0.3.18"
features = [
    "fmt",
    "tracing-log",
]

[dependencies.clap]
version  = "4.5.4"
features = [
    "derive",
]

[dependencies.serde]
version  = "1.0.197"
features = [
    "derive"
]

[dependencies.pingora]
# NOTE: For now we are tracking the git repo. We'll need
# to switch back to published versions before publishing
# river. We can coordinate with the `pingora` team for this.
#
# git = "https://github.com/cloudflare/pingora"
#
# NOTE: currently tracking https://github.com/cloudflare/pingora/pull/165
git = "https://github.com/memorysafety/pingora"
rev = "d8fb7dbe7558f32376b167e809932601c3bae40f"

[dependencies.pingora-core]
git = "https://github.com/memorysafety/pingora"
rev = "d8fb7dbe7558f32376b167e809932601c3bae40f"

[dependencies.pingora-proxy]
git = "https://github.com/memorysafety/pingora"
rev = "d8fb7dbe7558f32376b167e809932601c3bae40f"
