# Example configuration file
#
# All fields are optional, fields are shown with their
# default values.

[system]
# Threads per service
threads-per-service = 8

[[basic-proxy]]
name = "Example"
listeners = []
