# Test configuration file
#
# This is more in depth than the example

[system]
# Threads per service
threads-per-service = 8

[[basic-proxy]]
name = "Example1"

    [[basic-proxy.listeners]]
        [basic-proxy.listeners.source]
        kind = "Tcp"
            [basic-proxy.listeners.source.value]
            addr = "0.0.0.0:80"

    [[basic-proxy.listeners]]
        [basic-proxy.listeners.source]
        kind = "Tcp"
        [basic-proxy.listeners.source.value]
            addr = "0.0.0.0:443"
            [basic-proxy.listeners.source.value.tls]
                cert_path = "./assets/test.crt"
                key_path = "./assets/test.key"


[[basic-proxy]]
name = "Example2"
