name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Cancel old workflows for PRs (only the most recent workflow can run).
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

# Avoid workflow-level permissions, instead use job-level permissions.
permissions: {}

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./ci.sh
